In [1]:
data_list=[1,2,3]

In [2]:
data_list

[1, 2, 3]

In [5]:
import numpy as np

In [6]:
arr=np.array(data_list)

In [7]:
data_list2=[[10,20,30],[40,50,60],[70,80,90]]

In [8]:
arr2=np.array(data_list2
             )

In [9]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [10]:
arr3=np.array([1,2,3,4,5])

In [11]:
arr3

array([1, 2, 3, 4, 5])

In [12]:
arr2[0,1]

20

In [13]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [19]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [20]:
np.random.randint(0,10)

2

In [21]:
np.random.randint(1,10,5)

array([8, 3, 5, 3, 4])

In [23]:
np.random.rand(5)

array([0.81951681, 0.94952329, 0.98148954, 0.09992791, 0.03464571])

In [24]:
np.random.randn(5)

array([-0.96417573,  0.08895774, -1.64578497, -0.14601669, -0.51089411])

In [25]:
arr=np.arange(25)

In [26]:
ar

NameError: name 'ar' is not defined

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
newArray=np.random.randint(1,100,10)

In [31]:
newArray

array([38, 99, 10, 98, 56, 46, 71, 69, 38, 12])

In [32]:
newArray.max()

99

In [33]:
newArray.min()

10

In [35]:
newArray.sum()

537

In [36]:
newArray.mean()

53.7

In [37]:
newArray.argmax()

1

In [38]:
newArray.argmin()

2

In [39]:
detArray=np.random.randint(1,100,25)

In [40]:
detArray

array([79, 69, 71, 86, 35, 55, 83, 24, 95, 24, 60, 34, 24, 40, 76, 98, 58,
       65, 71, 73, 34, 15, 82, 36, 89])

In [41]:
detArray=detArray.reshape(5,5)

In [42]:
detArray

array([[79, 69, 71, 86, 35],
       [55, 83, 24, 95, 24],
       [60, 34, 24, 40, 76],
       [98, 58, 65, 71, 73],
       [34, 15, 82, 36, 89]])

In [43]:
np.linalg.det(detArray)

-654639.9999999461